trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

variables:
  acrServiceConnection: 'ACR-Service-Connection'
  acrLoginServer: 'unyleyaacrezequielfarias.azurecr.io'

steps:
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: $(acrServiceConnection)
